"""empty message

Revision ID: 352531818a0a
Revises: 816de8ce31df
Create Date: 2020-04-21 20:19:15.870018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352531818a0a'
down_revision = '816de8ce31df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sujet', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
